trigger:
- main  # Change this to your branch name

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'TerraformInitPlan'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      cd $(Build.SourcesDirectory)/path/to/your/terraform/code
      terraform init
      terraform plan -out=$(Build.ArtifactStagingDirectory)/tfplan
    displayName: 'Terraform Init and Plan'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'terraform-artifact'
      publishLocation: 'pipeline'

- deployment: 'TerraformApply'
  pool:
    vmImage: 'ubuntu-latest'
  environment: 'YourEnvironmentName'  # Create an environment in Azure DevOps
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: 'terraform-artifact'
        - script: |
            cd $(Pipeline.Workspace)/_work/*/terraform-artifact/path/to/your/terraform/code
            terraform apply -auto-approve $(Pipeline.Workspace)/_work/*/terraform-artifact/tfplan
          displayName: 'Terraform Apply'
