name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.29  # Replace with your desired version

    - name: Terraform Init
      run: |
        terraform --version
        terraform init -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var="some_variable=value"

    - name: Terraform Show
      run: terraform show
