trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'TerraformInitPlan'
  steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        cd $(Build.SourcesDirectory)/path/to/your/terraform/code
        echo 'provider "azurerm" { version = "=2.0.0" }' > main.tf  # Specify the version of the Azure provider
        terraform init
        terraform validate
        rm -f $(Build.ArtifactStagingDirectory)/tfplan  # Remove existing plan file
        terraform plan -out $(Build.ArtifactStagingDirectory)/tfplan
      displayName: 'Terraform Init and Plan'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'terraform-artifact'
        publishLocation: 'pipeline'

- deployment: 'TerraformApply'
  dependsOn: 'TerraformInitPlan'
  pool:
    vmImage: 'ubuntu-latest'
  environment: 'YourEnvironmentName'
  strategy:
    runOnce:
      deploy:
        steps:
          - download: current
            artifact: 'terraform-artifact'
            displayName: 'Download Terraform Artifact'

          - script: |
              cd $(Pipeline.Workspace)
              ls -la
              ls -la terraform-artifact

              # Apply the new Terraform plan
              terraform apply -auto-approve terraform-artifact/tfplan
            displayName: 'Terraform Apply'

          - script: |
              echo "Terraform Apply completed successfully."
            displayName: 'Terraform Apply Success Message'

          - script: |
              echo "Current Directory: $(pwd)"
              echo "Contents of Artifact Directory:"
              ls -la terraform-artifact
            displayName: 'Debugging Info'
