trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Terraform
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '3.x'

  - script: |
      echo "##vso[task.setvariable variable=TF_VAR_some_variable]your_variable_value"
    displayName: 'Set Terraform Variables'

  - script: |
      terraform --version
      terraform init
      terraform apply -auto-approve -var="some_variable=$(TF_VAR_some_variable)"
    displayName: 'Run Terraform'
