# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Terraform
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '3.x'

  - script: |
      echo "##vso[task.setvariable variable=TF_VAR_client_id]your_client_id"
      echo "##vso[task.setvariable variable=TF_VAR_client_secret]your_client_secret"
      echo "##vso[task.setvariable variable=TF_VAR_subscription_id]your_subscription_id"
      echo "##vso[task.setvariable variable=TF_VAR_tenant_id]your_tenant_id"
    displayName: 'Set Terraform Variables'

  - script: |
      terraform --version
      terraform init
      terraform apply -auto-approve -var="client_id=$(TF_VAR_client_id)" -var="client_secret=$(TF_VAR_client_secret)" -var="subscription_id=$(TF_VAR_subscription_id)" -var="tenant_id=$(TF_VAR_tenant_id)"
    displayName: 'Run Terraform'
