trigger:
- main  # Change this to your branch name if needed

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'Terraform'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      cd $(Build.SourcesDirectory)  # Change directory to your Terraform code location
      terraform init
      terraform validate
      terraform plan -out=tfplan
    displayName: 'Terraform Init and Plan'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'terraform-artifact'
      publishLocation: 'pipeline'

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'terraform-artifact'
      downloadPath: '$(Build.SourcesDirectory)/terraform-artifact'

  - script: |
      cd $(Build.SourcesDirectory)/terraform-artifact
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
